# Manually-written configuration for Nextcloud notification poller
cloud:
  endpoint: "cloud.example.com" # Domain of your Nextcloud
  user: "user" # You username in Nextcloud

polling:
  interval: 5 # Interval in seconds between polling requests

logging:
  file: "/data/data/com.termux/files/usr/var/log/notificator.log"
  level: info

app:
  cache: "/data/data/com.termux/files/usr/var/cache/notificator-cache" # Cache directory(created automatically)
  password: "/data/data/com.termux/files/usr/var/cache/notificator-auth" # app-password storage(created automatically)

